### ISSUE TITLE
运行后提示：数据解析出错

### ISSUE THREAD

**Issue by RookiePyl** [KwaiAppTeam/SwiftPamphletApp#118]
<img width="437" alt="数据解析出错" src="https://user-images.githubusercontent.com/15116300/148502314-9d5a8996-2b1c-423e-82c3-31c1c7eb3973.png">

👇是控制台的打印：

 [logging] volume does not support data protection, stripping SQLITE_OPEN_FILEPROTECTION_* flags
-- AppDelegate Section --
Metal API Validation Enabled

flock failed to lock list file (/var/folders/bb/h6cx64716jg5wlwjtz_n0jv40000gp/C/com.starming.SwiftPamphletApp//com.starming.SwiftPamphletApp/com.apple.metal/31001/libraries.list): errno = 35

**Comment by ming1016** [comment]
拉下最新代码吧，问题已修复 ，看看 static let pamphletIssueRepoName = "KwaiAppTeam/SwiftPamphletApp" 是不是这个。以前是 ming1016/SwiftPamphletApp 会有问题

**Comment by RookiePyl** [comment]
嗯 还是旧的。 新的已解决。
