### ISSUE TITLE
【建议】关于博客与资讯时间顺序问题

### ISSUE THREAD

**Issue by superleeyom** [KwaiAppTeam/SwiftPamphletApp#139]
我看有的「博客与咨询」是按时间降序，有的按时间升序，**能否统一最新文章或咨询在最前面**，否则如果文章较多，需要一直拖到最后面，望采纳
![image](https://user-images.githubusercontent.com/22115219/152755094-bf66f145-685a-41db-b2ae-361331e2cb25.png)

**Comment by ming1016** [comment]
最新提交已解决

**Comment by superleeyom** [comment]
@ming1016 非常感谢！

**Comment by superleeyom** [comment]
【建议】其实我觉得可以把APP的图标统一成big sur风格的，现有的APP icon和最新系统的风格不太协调

**Comment by ming1016** [comment]
这个可以，晚上回去做个

**Comment by superleeyom** [comment]
@ming1016 谢谢！

**Comment by ming1016** [comment]
已更新

**Comment by superleeyom** [comment]
谢谢戴老师！ @ming1016

**Comment by superleeyom** [comment]
戴老师，我不知道这个是不是bug，我在编译完后，已拉取最新的代码，打开APP，发现左侧的部分icon无法展示
![image](https://user-images.githubusercontent.com/22115219/153116135-1ee5a577-ec32-4549-bdca-1fe9fa0e4ae1.png)

**Comment by ming1016** [comment]
我提交了个更新，你再试试

**Comment by superleeyom** [comment]
经过验证，目前已修复，谢谢！ @ming1016
