### ISSUE TITLE
[bug] 右侧的侧边栏按钮，点击收起后，无法再次打开

### ISSUE THREAD

**Issue by superleeyom** [KwaiAppTeam/SwiftPamphletApp#171]
![swift](https://user-images.githubusercontent.com/22115219/156481805-3900df2b-1931-46ee-99fd-327c4937dadf.gif)

如gif图所示，必须要再次拉动第二栏到左边去才行，这里的交互逻辑有点bug
拉取的最新的代码，我自己用xcode编译的版本

**Comment by ming1016** [comment]
非常感谢你的反馈。问题已修复。你可以拉下最新代码。

**Comment by superleeyom** [comment]
@ming1016 好的，已经可以了，谢谢

**Comment by superleeyom** [comment]
![image](https://user-images.githubusercontent.com/22115219/156681610-a82fd2d6-9888-4746-92fe-24da9bd765e4.png)
戴老师，提个建议，就是右侧的展开按钮点击恢复后，二三级的菜单的宽度能够维持原有的宽度不变吗？

**Comment by ming1016** [comment]
还在找获取右侧宽度的方法，如果可以记住宽度，恢复时按照收起前宽度来就可以了。
