### ISSUE TITLE
[bug] 拉取最新版本的代码编译报错

### ISSUE THREAD

**Issue by superleeyom** [KwaiAppTeam/SwiftPamphletApp#174]
如图所示：
![image](https://user-images.githubusercontent.com/22115219/160073233-25d25d58-4794-4ccc-8671-d44716bb80d2.png)

**Comment by misalyn** [comment]
改成 try? content.write(toFile: "./Downloads/\(fileName)", atomically: true, encoding: String.Encoding.utf8)

**Comment by ming1016** [comment]
@superleeyom  已改，可以重新拉下代码

**Comment by superleeyom** [comment]
@ming1016 已解决，谢谢
